version: 2.1
orbs:
  android: circleci/android@2.0.0
jobs:
  build:
    docker:
      - image: cimg/android:2021.08.1
    steps:
      - checkout
      - run: ./gradlew androidDependencies
      - run: ./gradlew lint test